// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB05D7NNMNMwgA6KNKOwZfsLUScxV7a-48',
    appId: '1:466354460333:web:18aea04903e868c7ef5824',
    messagingSenderId: '466354460333',
    projectId: 'covid-19-tracker-app-dcdb9',
    authDomain: 'covid-19-tracker-app-dcdb9.firebaseapp.com',
    storageBucket: 'covid-19-tracker-app-dcdb9.firebasestorage.app',
    measurementId: 'G-BGDFWLT3NJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMs3MvoV-JHR92iqsXGiIXjwphtTKL6dk',
    appId: '1:466354460333:android:977fe277e084e344ef5824',
    messagingSenderId: '466354460333',
    projectId: 'covid-19-tracker-app-dcdb9',
    storageBucket: 'covid-19-tracker-app-dcdb9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpUJMej3Dl2LXI2Spz1aRQCsua0oVcsJI',
    appId: '1:466354460333:ios:293e4f411b04f52def5824',
    messagingSenderId: '466354460333',
    projectId: 'covid-19-tracker-app-dcdb9',
    storageBucket: 'covid-19-tracker-app-dcdb9.firebasestorage.app',
    iosBundleId: 'com.example.covidTracker',
  );
}
